source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EaseUI_Example', :exclusive => true do
  pod 'EaseUI', :path => '../'
end

target 'EaseUI_Tests', :exclusive => true do
  pod 'EaseUI', :path => '../'

  
end
